# Generated by Django 4.2.2 on 2023-07-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
