# Generated by Django 4.2.2 on 2023-06-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('opinion', models.TextField(max_length=200)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='plato',
            old_name='nombre',
            new_name='nombre_plato',
        ),
    ]
