# Generated by Django 4.2 on 2023-07-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('img', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
